import { type NextPage } from "next";
import Head from "next/head";
import { SignInButton, UserButton, useUser } from "@clerk/nextjs";
import { SignOutButton } from "@clerk/clerk-react";
import { api } from "~/utils/api";
const Home: NextPage = () => {
  const user = useUser();

  const { data } = api.posts.getAll.useQuery();

  return (
    <>
      <Head>
        <title>chirp</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <div>
            {" "}
            {!user.isSignedIn && <SignInButton />}{" "}
            {!!user.isSignedIn && <SignOutButton />}
          </div>

          <div>
            {data?.map((post) => (
              <div key={post.id}>{post.content}</div>
            ))}{" "}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
